#!/usr/bin/env ruby
# encoding: UTF-8

$LOAD_PATH.unshift '.'
require_relative 'lib/downloader.rb'
Signal.trap('INT') {}

# # TODO: GEt Opts
# 2 Opts
# Move this to SynologyDownloader.run

fetcher = SDD::Downloader.new
fetcher.run
