#!/usr/bin/env ruby
# encoding: UTF-8

$LOAD_PATH.unshift '.'
require_relative 'lib/synologydownloader.rb'
Signal.trap('INT') {}



# # TODO: GEt Opts
# 2 Opts

# 1. Download (current standard)

# 2. Move files in Downloads to Series
# Search for video-types in download-folder.
# if series move it to Series/ShowName/Season
# if Movie, Move it to /video/movies/New Movies


fetcher = SynologyDownloader.new
fetcher.move_start
fetcher.load_rss
fetcher.save_db if fetcher.download_start
